Repository flytegg/ls-discord-bot, pull requests merged in 2022-12, with the labels that each got.

#11 Missing contrib
  build.gradle.kts
  src/main/kotlin/com/learnspigot/bot/manager/ForumManager.kt
Labels: bug, high priority, needs testing

#18 Fix capitalisation & link GNU License
  README.md
Labels: enhancement, medium priority

#25 Sanitize query string & bias exact match score
  src/main/kotlin/com/learnspigot/bot/util/LectureSearcher.kt
Labels: bug, high priority, needs testing

#19 /repleaderboard now uses mentions + leaderboard now shows "last updated" with localized timestamp
  src/main/kotlin/com/learnspigot/bot/command/ReputationCommand.kt
  src/main/kotlin/com/learnspigot/bot/manager/LeaderboardManager.kt
Labels: enhancement, medium priority

#32 Contributors in help tickets may now be selected by management/roles with the "Manage Server" permission.
  src/main/kotlin/com/learnspigot/bot/manager/ForumManager.kt
Labels: bug, enhancement

#17 Add TSLA Stock Command
  src/main/kotlin/com/learnspigot/bot/LearnSpigotBot.kt
  src/main/kotlin/com/learnspigot/bot/command/TeslaStockCommand.kt
  src/test/kotlin/com/learnspigot/bot/test/http/FinanceServiceTest.kt
Labels: enhancement, good first issue, low priority

#37 Workflows
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: enhancement

#33 Non-bot messages will now be deleted in the suggestions channel.
  src/main/kotlin/com/learnspigot/bot/LearnSpigotBot.kt
  src/main/kotlin/com/learnspigot/bot/listener/SuggestionChannelListener.kt
Labels: enhancement

#36 Fixes issue with repleaderboard
  src/main/kotlin/com/learnspigot/bot/command/ReputationCommand.kt
Labels: bug

#35 Pin new forum post messages and delete pin.
  src/main/kotlin/com/learnspigot/bot/manager/ForumManager.kt
Labels: enhancement

#55 Fixes previous issue of wrong reps being removed when a timestamp was specified
  src/main/kotlin/com/learnspigot/bot/command/ReputationCommand.kt
Labels: bug

#60 Toggle command with adding roles to ping specific people when a rep is added
  src/main/kotlin/com/learnspigot/bot/LearnSpigotBot.kt
  src/main/kotlin/com/learnspigot/bot/command/ToggleCommand.kt
  src/main/kotlin/com/learnspigot/bot/entity/UserProfile.kt
Labels: enhancement

#59 Messages from the bot are now deleted + contributors are shown when a thread is closed
  src/main/kotlin/com/learnspigot/bot/manager/ForumManager.kt
Labels: enhancement

#74 Basic poll command
  src/main/kotlin/com/learnspigot/bot/LearnSpigotBot.kt
  src/main/kotlin/com/learnspigot/bot/command/PollCommand.kt
  src/main/kotlin/com/learnspigot/bot/manager/PollManager.kt
Labels: enhancement, low priority
